# Generated by Django 5.2.1 on 2026-03-20 05:23

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "subdomain",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("state", models.CharField(blank=True, max_length=255, null=True)),
                ("kind", models.CharField(blank=True, max_length=255, null=True)),
                ("scraper", models.CharField(blank=True, max_length=255, null=True)),
                ("pages", models.IntegerField(blank=True, null=True)),
                ("start_year", models.IntegerField(blank=True, null=True)),
                ("extra", models.JSONField(blank=True, max_length=255, null=True)),
                ("country", models.CharField(blank=True, max_length=255, null=True)),
                ("lat", models.CharField(blank=True, max_length=255, null=True)),
                ("lng", models.CharField(blank=True, max_length=255, null=True)),
                ("has_finance_data", models.BooleanField(default=False)),
                (
                    "current_stage",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("fetch_total", models.IntegerField(default=0)),
                ("fetch_completed", models.IntegerField(default=0)),
                ("fetch_failed", models.IntegerField(default=0)),
                ("ocr_total", models.IntegerField(default=0)),
                ("ocr_completed", models.IntegerField(default=0)),
                ("ocr_failed", models.IntegerField(default=0)),
                ("compilation_total", models.IntegerField(default=0)),
                ("compilation_completed", models.IntegerField(default=0)),
                ("compilation_failed", models.IntegerField(default=0)),
                ("extraction_total", models.IntegerField(default=0)),
                ("extraction_completed", models.IntegerField(default=0)),
                ("extraction_failed", models.IntegerField(default=0)),
                ("deploy_total", models.IntegerField(default=0)),
                ("deploy_completed", models.IntegerField(default=0)),
                ("deploy_failed", models.IntegerField(default=0)),
                ("coordinator_enqueued", models.BooleanField(default=False)),
                (
                    "last_error_stage",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("last_error_message", models.TextField(blank=True, null=True)),
                ("last_error_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "extraction_status",
                    models.CharField(default="pending", max_length=255),
                ),
                (
                    "last_updated",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "last_deployed",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "last_extracted",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
            options={
                "db_table": "sites",
                "ordering": ["-pages"],
                "managed": False,
            },
        ),
    ]
