# Generated by Django 5.2.1 on 2026-02-20 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Site",
            fields=[
                (
                    "subdomain",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("state", models.CharField(blank=True, max_length=255, null=True)),
                ("country", models.CharField(blank=True, max_length=255, null=True)),
                ("kind", models.CharField(blank=True, max_length=255, null=True)),
                ("pages", models.IntegerField(blank=True, null=True)),
                (
                    "last_updated",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("lat", models.CharField(blank=True, max_length=255, null=True)),
                ("lng", models.CharField(blank=True, max_length=255, null=True)),
                ("has_finance_data", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "sites",
                "ordering": ["-pages"],
                "managed": False,
            },
        ),
    ]
