"""
Django settings for civic_django project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
import warnings
from pathlib import Path

import djp
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# Set DEBUG=true in environment to enable debug mode
DEBUG = os.environ.get("DEBUG", "false").lower() in ("true", "1", "yes")


def get_env_variable(var_name, default=None):
    """Get the environment variable or return exception"""
    try:
        return os.environ[var_name]
    except KeyError as exc:
        error_msg = f"Set the {var_name} env variable"
        if DEBUG or default is not None:
            warnings.warn(error_msg, stacklevel=2)
            return default
        else:
            raise ImproperlyConfigured(error_msg) from exc


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_env_variable(
    "SECRET_KEY", "django-insecure--5$173iss#xti=h+b7zi4x5ogh$*kvg)kb4xsx%71(rctn%vwe"
)


ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "alameda.ca.civic.dev",
    "0.0.0.0",
    "civic.band",
    "*.civic.band",
    "vscode.civic.town",
    "adversely-star-koala.edgecompute.app",
    "*.adversely-star-koala.edgecompute.app",
]

ROOT_DOMAINS = ["civic.band", "adversely-star-koala.edgecompute.app"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "social_django",
    "pages",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "social_django.context_processors.backends",
                "social_django.context_processors.login_redirect",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

# Use clerk's Postgres database (shared with clerk workers)
# Falls back to SQLite for local development if DATABASE_URL not set
import dj_database_url

DATABASE_URL = os.environ.get("DATABASE_URL")

if DATABASE_URL:
    # Parse DATABASE_URL using dj-database-url
    DATABASES = {"default": dj_database_url.parse(DATABASE_URL)}
else:
    # Fallback to SQLite for local development
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "sites.db",
        },
    }


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Authentication backends
# https://python-social-auth.readthedocs.io/en/latest/configuration/django.html
AUTHENTICATION_BACKENDS = (
    "social_core.backends.open_id_connect.OpenIdConnectAuth",
    "django.contrib.auth.backends.ModelBackend",
)

# Social Auth Configuration
SOCIAL_AUTH_OIDC_OIDC_ENDPOINT = os.environ.get("OIDC_ENDPOINT")
SOCIAL_AUTH_OIDC_KEY = os.environ.get("OIDC_CLIENT_ID")
SOCIAL_AUTH_OIDC_SECRET = os.environ.get("OIDC_CLIENT_SECRET")

# Additional OIDC settings
SOCIAL_AUTH_OIDC_SCOPE = ["openid", "email", "profile"]
SOCIAL_AUTH_OIDC_ID_TOKEN_DECRYPTION_KEY = SOCIAL_AUTH_OIDC_SECRET

# Redirect URLs after authentication
LOGIN_URL = "/admin/login/"
LOGIN_REDIRECT_URL = "/admin/"
LOGOUT_REDIRECT_URL = "/"

# Social Auth pipeline (default pipeline, can be customized)
SOCIAL_AUTH_PIPELINE = (
    "social_core.pipeline.social_auth.social_details",
    "social_core.pipeline.social_auth.social_uid",
    "social_core.pipeline.social_auth.auth_allowed",
    "social_core.pipeline.social_auth.social_user",
    "social_core.pipeline.user.get_username",
    "social_core.pipeline.user.create_user",
    "social_core.pipeline.social_auth.associate_user",
    "social_core.pipeline.social_auth.load_extra_data",
    "social_core.pipeline.user.user_details",
)


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "dist"
STATICFILES_DIRS = [BASE_DIR / "static"]

STATICFILES_FINDERS = (
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
)

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

import logging.config

from django.utils.log import DEFAULT_LOGGING

# Disable Django's logging setup
LOGGING_CONFIG = None

# Log level can be set via environment variable
LOGLEVEL = os.environ.get("LOGLEVEL", "info").upper()

# Check if JSON logging is available
try:
    import pythonjsonlogger.json  # noqa: F401

    _json_logging_available = True
except ImportError:
    _json_logging_available = False

# Use JSON logging in production if available, plain text otherwise
_default_format = "json" if (not DEBUG and _json_logging_available) else "plain"
LOG_FORMAT = os.environ.get("LOG_FORMAT", _default_format)

# Fall back to plain if JSON requested but not available
if LOG_FORMAT == "json" and not _json_logging_available:
    LOG_FORMAT = "plain"

# Build formatters dict - only include JSON if available
_formatters = {
    "plain": {
        "format": "%(asctime)s %(name)-12s %(levelname)-8s %(message)s",
    },
    "django.server": DEFAULT_LOGGING["formatters"]["django.server"],
}

if _json_logging_available:
    _formatters["json"] = {
        "()": "pythonjsonlogger.json.JsonFormatter",
        "format": "%(asctime)s %(name)s %(levelname)s %(message)s",
        "timestamp": True,
    }

logging.config.dictConfig(
    {
        "version": 1,
        "disable_existing_loggers": False,
        "formatters": _formatters,
        "handlers": {
            # console logs to stderr with configured format
            "console": {
                "class": "logging.StreamHandler",
                "formatter": LOG_FORMAT,
            },
            "django.server": DEFAULT_LOGGING["handlers"]["django.server"],
        },
        "loggers": {
            # default for all undefined Python modules
            "": {
                "level": "WARNING",
                "handlers": ["console"],
            },
            # Our application code
            "django_plugins": {
                "level": LOGLEVEL,
                "handlers": ["console"],
                "propagate": False,
            },
            "plugins": {
                "level": LOGLEVEL,
                "handlers": ["console"],
                "propagate": False,
            },
            # Default runserver request logging
            "django.server": DEFAULT_LOGGING["loggers"]["django.server"],
        },
    }
)


DJP_PLUGINS_DIR = [BASE_DIR / "django_plugins"]


# API Key Authentication Settings
REDIS_URL = get_env_variable("REDIS_URL", "redis://localhost:6379")
CIVIC_OBSERVER_URL = get_env_variable("CIVIC_OBSERVER_URL", "http://localhost:8080")
CIVIC_OBSERVER_SECRET = get_env_variable(
    "CIVIC_OBSERVER_SECRET", "dev-secret-change-me"
)
CIVIC_BAND_DOMAIN = get_env_variable("CIVIC_BAND_DOMAIN", "civic.band")

# Cache TTLs (in seconds)
API_KEY_VALID_TTL = 7200  # 2 hours for valid keys
API_KEY_INVALID_TTL = 300  # 5 minutes for invalid keys


djp.settings(globals())
